# Generated by Django 5.2.3 on 2025-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='product_datasheets/'),
        ),
    ]
