# Generated by Django 5.2.3 on 2025-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_datasheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rack_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
