# Generated by Django 5.2.3 on 2025-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
